
NAME := board_linuxhost

MODULE              := 1062
HOST_ARCH           := linux
HOST_MCU_FAMILY     := linux

$(NAME)_COMPONENTS  :=  tfs

CONFIG_LIB_TFS := y
CONFIG_TFS_ID2_RSA := y
CONFIG_TFS_ID2_3DES := n
CONFIG_TFS_EMULATE := n
CONFIG_TFS_ON_LINE := n
CONFIG_TFS_OPENSSL := n
CONFIG_TFS_MBEDTLS := n
CONFIG_TFS_ALICRYPTO := n
CONFIG_TFS_DEBUG := n
CONFIG_TFS_TEE := n
CONFIG_TFS_SW := y
CONFIG_TFS_TEST := n


CURRENT_TIME = $(shell /bin/date +%Y%m%d.%H%M)
CONFIG_SYSINFO_KERNEL_VERSION = YOS-R-1.0.1

ifneq (,${BINS})
GLOBAL_CFLAGS += -DSYSINFO_OS_BINS
CONFIG_SYSINFO_APP_VERSION = APP-1.0.0-$(CURRENT_TIME)
define get-os-version
${CONFIG_SYSINFO_KERNEL_VERSION}_$(CONFIG_SYSINFO_APP_VERSION)
endef
else
define get-os-version
${CONFIG_SYSINFO_KERNEL_VERSION}-$(CURRENT_TIME)
endef
endif

CONFIG_SYSINFO_OS_VERSION := $(call get-os-version)
CONFIG_SYSINFO_PRODUCT_MODEL := ALI_YOS_LINUXHOST
CONFIG_SYSINFO_DEVICE_NAME := LINUXHOST

GLOBAL_CFLAGS += -DSYSINFO_OS_VERSION=\"$(CONFIG_SYSINFO_OS_VERSION)\"
GLOBAL_CFLAGS += -DSYSINFO_KERNEL_VERSION=\"$(CONFIG_SYSINFO_KERNEL_VERSION)\"
GLOBAL_CFLAGS += -DSYSINFO_APP_VERSION=\"$(CONFIG_SYSINFO_APP_VERSION)\"
GLOBAL_CFLAGS += -DSYSINFO_PRODUCT_MODEL=\"$(CONFIG_SYSINFO_PRODUCT_MODEL)\"
GLOBAL_CFLAGS += -DSYSINFO_DEVICE_NAME=\"$(CONFIG_SYSINFO_DEVICE_NAME)\"

GLOBAL_CFLAGS += -m32  -std=gnu99
GLOBAL_LDFLAGS += -m32

#CONFIG_COAP_DTLS_SUPPORT := y
#CONFIG_COAP_ONLINE := y

CONFIG_OTA_CH := alink
#alink/coap/mqtt

